export interface TreatmentOption {
    name: string;
    dosage: string; // Display string e.g. "10ml per 15L Pump"
    dosagePerAcre: number; // For calculator e.g. 100
    unit: 'ml' | 'g' | 'kg';
    type: 'Organic' | 'Chemical' | 'Cultural' | 'Tonic';
    brand?: string;
    composition?: string; // e.g. "Imidacloprid 17.8% SL"
    cost?: string;
    image?: string; // URL to product image
}

export interface TreatmentStage {
    stageName: string; // e.g. "Immediate Spray (Tank Mix)"
    stageNameMarathi?: string;
    description: string; // "Mix these two for best results"
    descriptionMarathi?: string;
    products: TreatmentOption[];
}

export interface DiseaseInfo {
    name: string;
    localName: string;
    description: string;
    cause: string;
    causeMarathi?: string;
    symptoms: string[];
    symptomsMarathi?: string[];
    preventiveMeasures: string[];
    preventiveMeasuresMarathi?: string[];
    treatmentPlan: TreatmentStage[];
    severity: 'Low' | 'Medium' | 'High';
    detailedDescription?: string;
    detailedDescriptionMarathi?: string;
    images?: string[];
    lookalikes?: string[]; // Keys of similar diseases for visual verification
    isGemini?: boolean; // Flag to indicate if the diagnosis was generated by Gemini AI
}

// Local Image Paths (Generated Assets)
const IMG_PESTICIDE = '/images/pesticide.png';
const IMG_FUNGICIDE = '/images/fungicide.png';
const IMG_TONIC = '/images/tonic.png';

export const DISEASE_DB: Record<string, DiseaseInfo> = {
    // --- COTTON ---
    'Cotton_Healthy': {
        // ... (existing fields)
        name: 'Healthy Cotton',
        localName: 'Nirogi Kapus (निरोगी कापूस)',
        description: 'Your crop looks healthy and vigorous! No immediate action needed.',
        cause: 'Good agricultural practices.',
        causeMarathi: 'चांगल्या कृषी पद्धती.',
        symptoms: ['Green leaves', 'No spots', 'Healthy growth'],
        symptomsMarathi: ['हिरवी पाने', 'ठिपके नाहीत', 'चांगली वाढ'],
        preventiveMeasures: ['Continue monitoring weekly', 'Maintain proper irrigation'],
        preventiveMeasuresMarathi: ['दर आठवड्याला पाहणी करा', 'योग्य पाणीपुरवठा ठेवा'],
        treatmentPlan: [],
        severity: 'Low',
        detailedDescription: 'The crop is in good condition. Regular monitoring is sufficient.',
        detailedDescriptionMarathi: 'पीक चांगल्या स्थितीत आहे. नियमित पाहणी करणे पुरेसे आहे.',
        images: ['/images/diseases/cotton_healthy.png'],
        lookalikes: ['Cotton_Disease_Red_Leaf_Curl'] // Verify against symptoms if unsure
    },
    'Cotton_Disease_Red_Leaf_Curl': {
        // ...
        name: 'Red Leaf Curl / Blight',
        localName: 'Lalya / Bokdya (लाल्या / बोकड्या)',
        description: 'Severe stress caused by sucking pests and nutrient deficiency.',
        cause: 'Sucking pests (Thrips/Aphids) + Magnesium Deficiency.',
        causeMarathi: 'रस शोषणारी कीड (मावा/तुडतुडे) आणि मॅग्नेशियमची कमतरता.',
        symptoms: ['Reddening of leaves', 'Upward curling (Cup shape)', 'Stunted growth'],
        symptomsMarathi: ['पाने लाल होणे', 'पाने वरच्या बाजूला वाकणे', 'वाढ खुंटणे'],
        preventiveMeasures: ['Use resistant varieties', 'Install Yellow Sticky Traps'],
        preventiveMeasuresMarathi: ['प्रतिकारक्षम वाण वापरा', 'पिवळे चिकट सापळे लावा'],
        treatmentPlan: [
            {
                stageName: 'Step 1: Control Spray (Tank Mix)',
                stageNameMarathi: 'फवारणी १: कीड नियंत्रण (मिश्रण)',
                description: 'Mix Insecticide with Tonic for recovery.',
                products: [
                    {
                        name: 'Imidacloprid',
                        brand: 'Confidor',
                        composition: 'Imidacloprid 17.8% SL',
                        dosage: '0.5 ml per Liter',
                        dosagePerAcre: 100,
                        unit: 'ml',
                        type: 'Chemical',
                        cost: '₹450/100ml',
                        image: IMG_PESTICIDE
                    },
                    {
                        name: 'Magnesium Sulphate',
                        brand: 'Agri-Mag',
                        composition: 'MgSO4 Fertilizer',
                        dosage: '5g per Liter',
                        dosagePerAcre: 1000,
                        unit: 'g',
                        type: 'Tonic',
                        cost: '₹80/kg',
                        image: IMG_TONIC
                    }
                ]
            },
            {
                stageName: 'Step 2: Organic Booster (After 5 Days)',
                stageNameMarathi: 'फवारणी २: जैविक टॉनिक (५ दिवसांनंतर)',
                description: 'To boost immunity and growth.',
                products: [
                    {
                        name: 'Neem Oil',
                        brand: 'Nisarga',
                        composition: 'Azadirachtin 10000 ppm',
                        dosage: '2-3 ml per Liter',
                        dosagePerAcre: 500,
                        unit: 'ml',
                        type: 'Organic',
                        cost: '₹300/L',
                        image: IMG_PESTICIDE
                    }
                ]
            }
        ],
        severity: 'High',
        detailedDescription: 'Reddening of leaves in cotton is a physiological disorder often caused by magnesium deficiency and sucking pest damage. The leaves turn red, curl upwards, and eventually dry out, leading to yield loss.',
        detailedDescriptionMarathi: 'कापसाची पाने लाल पडणे हा एक विकृती आहे जो मॅग्नेशियमची कमतरता आणि रस शोषणार्‍या किडींमुळे होतो. पाने लाल होऊन वाकतात आणि वाळतात.',
        images: ['/images/diseases/cotton_curl.png'],
        lookalikes: ['Cotton_Healthy']
    },

    // --- SOYBEAN ---
    'Soybean_Healthy': {
        name: 'Healthy Soybean',
        localName: 'Nirogi Soybean (निरोगी सोयाबीन)',
        description: 'Excellent foliage. Keep monitoring for early signs of rust.',
        cause: 'Good management.',
        causeMarathi: 'चांगले व्यवस्थापन.',
        symptoms: ['Dark green leaves', 'No yellowing', 'Healthy pods'],
        symptomsMarathi: ['गडद हिरवी पाने', 'पिवळेपणा नाही'],
        preventiveMeasures: ['Monitor for caterpillars'],
        preventiveMeasuresMarathi: ['अळीसाठी निरीक्षण करा'],
        treatmentPlan: [],
        severity: 'Low',
        detailedDescription: 'The soybean crop is healthy with dark green foliage. No signs of disease or pest infestation.',
        detailedDescriptionMarathi: 'सोयाबीन पीक निरोगी असून पाने गडद हिरवी आहेत. कीड किंवा रोगाची लक्षणे नाहीत.',
        images: ['/images/diseases/soybean_healthy.png'],
        lookalikes: ['Soybean_Mosaic_Virus', 'Soybean_Brown_Spot']
    },
    'Soybean_Mosaic_Virus': {
        name: 'Soybean Mosaic Virus (SMV)',
        localName: 'Mosaic Rog (मोझॅक रोग)',
        description: 'Viral disease transmitted by aphids.',
        cause: 'Soybean Mosaic Virus (Aphid Vector).',
        causeMarathi: 'सोयाबीन मोझॅक व्हायरस (मावा किडीमुळे).',
        symptoms: ['Mosaic pattern', 'Leaf puckering', 'Stunted plants'],
        symptomsMarathi: ['पानांवर पिवळे-हिरवे पट्टे', 'पाने आकसणे', 'वाढ खुंटणे'],
        preventiveMeasures: ['Remove infected plants (Roguing)', 'Control Aphids'],
        preventiveMeasuresMarathi: ['रोगी झाडे उपटून टाका', 'मावा नियंत्रण करा'],
        treatmentPlan: [
            {
                stageName: 'Vector Control',
                stageNameMarathi: 'कीड नियंत्रण',
                description: 'Control aphids to stop spread.',
                products: [
                    {
                        name: 'Thiamethoxam',
                        brand: 'Actara',
                        composition: 'Thiamethoxam 25% WG',
                        dosage: '10g per 15L Pump',
                        dosagePerAcre: 100,
                        unit: 'g',
                        type: 'Chemical',
                        cost: '₹180/100g',
                        image: IMG_PESTICIDE
                    }
                ]
            }
        ],
        severity: 'Medium',
        detailedDescription: 'Soybean Mosaic Virus (SMV) causes stunted growth and puckered leaves. It is transmitted by aphids and infected seeds. Yield reduction can be significant if not managed early.',
        detailedDescriptionMarathi: 'सोयाबीन मोझॅक व्हायरसमुळे वाढ खुंटते आणि पाने आकसतात. हा रोग मावा कीड आणि बाधित बियाण्यांमार्फत पसरतो.',
        images: ['/images/diseases/soybean_mosaic.png'],
        lookalikes: ['Soybean_Healthy']
    },
    'Soybean_Brown_Spot': {
        name: 'Septoria Brown Spot',
        localName: 'Tapkiri Thipke (तपकिरी ठिपके)',
        description: 'Fungal infection on lower leaves.',
        cause: 'Fungus: Septoria glycines',
        causeMarathi: 'बुरशी: सेप्टोरिया ग्लायसिन्स',
        symptoms: ['Brown irregular spots', 'Yellowing leaves'],
        symptomsMarathi: ['तपकिरी ठिपके', 'पाने पिवळी पडणे'],
        preventiveMeasures: ['Improve air circulation'],
        preventiveMeasuresMarathi: ['हवा खेळती ठेवा'],
        treatmentPlan: [
            {
                stageName: 'Fungicide Spray',
                stageNameMarathi: 'बुरशीनाशक फवारणी',
                description: 'Apply broad spectrum fungicide.',
                products: [
                    {
                        name: 'Carbendazim + Mancozeb',
                        brand: 'Saaf',
                        composition: 'Carbendazim 12% + Mancozeb',
                        dosage: '2.5g per Liter',
                        dosagePerAcre: 500,
                        unit: 'g',
                        type: 'Chemical',
                        cost: '₹500/kg',
                        image: IMG_FUNGICIDE
                    }
                ]
            }
        ],
        severity: 'Medium',
        detailedDescription: 'Septoria Brown Spot is a common fungal disease that starts on lower leaves. It thrives in warm, wet conditions and causes premature leaf drop.',
        detailedDescriptionMarathi: 'सेप्टोरिया ब्राउन स्पॉट हा कवकजन्य रोग खालच्या पानांवर सुरू होतो. उबदार आणि आर्द्र हवामानात हा वाढतो आणि पाने अकाली गळतात.',
        images: ['/images/diseases/soybean_spot.png'],
        lookalikes: ['Soybean_Frog_Eye_Spot'] // Confusable
    },
    'Soybean_Frog_Eye_Spot': {
        name: 'Frog Eye Leaf Spot',
        localName: 'Beduk Dola (बेडूक डोळा)',
        description: 'Fungal spots resembling frog eyes.',
        cause: 'Fungus: Cercospora sojina',
        causeMarathi: 'बुरशी: सर्कोस्पोरा सोजना',
        symptoms: ['Eye-like spots (Gray center, Red border)'],
        symptomsMarathi: ['बेडकाच्या डोळ्यासारखे ठिपके'],
        preventiveMeasures: ['Use resistant varieties'],
        preventiveMeasuresMarathi: ['प्रतिकारक्षम वाण वापरा'],
        treatmentPlan: [
            {
                stageName: 'Curative Spray',
                stageNameMarathi: 'उपचारात्मक फवारणी',
                description: 'Strong fungicide required.',
                products: [
                    {
                        name: 'Azoxystrobin',
                        brand: 'Amistar',
                        composition: 'Azoxystrobin 23% SC',
                        dosage: '1 ml per Liter',
                        dosagePerAcre: 200,
                        unit: 'ml',
                        type: 'Chemical',
                        cost: '₹1200/200ml',
                        image: IMG_FUNGICIDE
                    }
                ]
            }
        ],
        severity: 'Medium',
        detailedDescription: 'Frog Eye Leaf Spot produces circular spots with a gray center and reddish-brown border. It can significantly reduce seed quality and yield if it spreads to pods.',
        detailedDescriptionMarathi: 'फ्रॉग आय लीफ स्पॉटमुळे करड्या मध्यासह आणि लालसर-तपकिरी कडा असलेले गोल ठिपके पडतात. शेंगांवर पसरल्यास उत्पादनावर परिणाम होतो.',
        images: ['/images/diseases/soybean_frogeye.png'],
        lookalikes: ['Soybean_Brown_Spot'] // Confusable
    }
};
