export const PLANT_KEYWORDS = [
    'plant', 'leaf', 'flower', 'vegetable', 'fruit', 'tree', 'crop', 'agriculture', 'soil', 'flora', 'herb', 'shrub', 'grass', 'bud', 'stem', 'root', 'seed', 'seedling', 'sprout', 'photosynthesis', 'botany', 'garden', 'orchard', 'farm', 'plantation', 'vineyard', 'greenhouse', 'nursery', 'field', 'meadow', 'pasture', 'lawn', 'park', 'forest', 'jungle', 'woodland', 'grove', 'thicket', 'bush', 'weed', 'moss', 'fern', 'algae', 'fungus', 'mushroom', 'lichen', 'pollen', 'nectar', 'petal', 'sepal', 'stamen', 'pistil', 'ovary', 'fruit', 'nut', 'berry', 'grain', 'cereal', 'wheat', 'rice', 'corn', 'maize', 'barley', 'oats', 'rye', 'millet', 'sorghum', 'bamboo', 'sugarcane', 'cotton', 'flax', 'hemp', 'jute', 'sisal', 'rubber', 'tobacco', 'coffee', 'tea', 'cocoa', 'spice', 'herb', 'medicinal', 'aromatic', 'perfume', 'dye', 'oil', 'fiber', 'timber', 'lumber', 'wood', 'pulp', 'paper', 'biomass', 'biofuel', 'fodder', 'forage', 'silage', 'hay', 'straw', 'compost', 'manure', 'fertilizer', 'pesticide', 'insecticide', 'fungicide', 'herbicide', 'weedicide', 'nematicide', 'acaricide', 'rodenticide', 'bactericide', 'algaecide', 'molluscicide', 'avicide', 'piscicide', 'plant', 'leaf', 'flower'
];

export const BLOCK_KEYWORDS = [
    'person', 'man', 'woman', 'face', 'human', 'selfie', 'body', 'skin', 'hand', 'leg', 'foot', 'arm', 'chest', 'back', 'head', 'hair', 'eye', 'nose', 'mouth', 'ear', 'finger', 'toe', 'nail', 'tooth', 'tongue', 'lip', 'shoulder', 'elbow', 'wrist', 'knee', 'ankle', 'heel', 'keyboard', 'computer', 'laptop', 'monitor', 'screen', 'phone', 'mobile', 'tablet', 'mouse', 'desk', 'table', 'chair', 'furniture', 'room', 'wall', 'floor', 'ceiling', 'window', 'door', 'car', 'vehicle', 'road', 'building', 'house', 'city', 'street', 'sky', 'cloud', 'sun', 'moon', 'star', 'space', 'universe', 'planet', 'galaxy', 'nebula', 'comet', 'asteroid', 'meteor', 'satellite', 'rocket', 'spaceship', 'alien', 'ufo', 'monster', 'zombie', 'ghost', 'vampire', 'werewolf', 'witch', 'wizard', 'dragon', 'dinosaur', 'robot', 'machine', 'engine', 'motor', 'gear', 'wheel', 'tire', 'brake', 'pedal', 'steering', 'dashboard', 'seat', 'belt', 'airbag', 'bumper', 'lights', 'mirror', 'window', 'door', 'hood', 'trunk', 'roof', 'undercarriage', 'exhaust', 'muffler', 'catalytic', 'converter', 'transmission', 'suspension', 'brakes', 'radiator', 'battery', 'alternator', 'starter', 'ignition', 'fuel', 'tank', 'pump', 'filter', 'injector', 'carburetor', 'spark', 'plug', 'wire', 'cable', 'fuse', 'relay', 'switch', 'sensor', 'computer', 'module', 'controller', 'actuator', 'motor', 'pump', 'valve', 'solenoid', 'cylinder', 'piston', 'crankshaft', 'camshaft', 'rod', 'bearing', 'seal', 'gasket', 'bolt', 'nut', 'screw', 'washer', 'clip', 'clamp', 'hose', 'pipe', 'tube', 'wire', 'cable', 'connector', 'terminal', 'socket', 'plug', 'switch', 'button', 'knob', 'dial', 'gauge', 'meter', 'display', 'screen', 'monitor', 'keyboard', 'mouse', 'laptop', 'tablet', 'phone', 'camera', 'microphone', 'speaker', 'headphone', 'earphone', 'printer', 'scanner', 'copier', 'fax'
];

export const CONFLICT_CROPS = [
    'corn', 'maize', 'wheat', 'rice', 'paddy', 'sugarcane', 'tomato', 'potato', 'onion', 'garlic', 'chili', 'pepper', 'brinjal', 'eggplant', 'okra', 'ladyfinger', 'cabbage', 'cauliflower', 'broccoli', 'spinach', 'lettuce', 'carrot', 'radish', 'turnip', 'beetroot', 'cucumber', 'pumpkin', 'squash', 'melon', 'watermelon', 'gourd', 'bean', 'pea', 'lentil', 'gram', 'chickpea', 'pigeonpea', 'moong', 'urad', 'soybean', 'groundnut', 'peanut', 'sunflower', 'safflower', 'mustard', 'sesame', 'castor', 'linseed', 'coconut', 'arecanut', 'oilpalm', 'rubber', 'coffee', 'tea', 'cocoa', 'cashew', 'mango', 'banana', 'papaya', 'guava', 'citrus', 'lemon', 'lime', 'orange', 'grape', 'pomegranate', 'apple', 'pear', 'peach', 'plum', 'apricot', 'cherry', 'strawberry', 'raspberry', 'blackberry', 'blueberry', 'cranberry', 'gooseberry', 'currant', 'grapefruit', 'pomelo', 'jackfruit', 'pineapple', 'litchi', 'sapota', 'custardapple', 'fig', 'date', 'ber', 'aonla', 'tamarind', 'woodapple', 'bael'
];
